version: "3"
services:
  pgsql1:
    container_name: pgsql1
    image: postgres:11.1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pflow
      POSTGRES_PASSWORD: pflow
      POSTGRES_DB: pflow
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      pgnet:
        aliases:
          - pgsql1
networks:
  pgnet:
    driver: bridge
