// Code generated by protoc-gen-go. DO NOT EDIT.
// source: event.proto

package finite

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type JsonPayload struct {
	Json                 []byte   `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JsonPayload) Reset()         { *m = JsonPayload{} }
func (m *JsonPayload) String() string { return proto.CompactTextString(m) }
func (*JsonPayload) ProtoMessage()    {}
func (*JsonPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{0}
}

func (m *JsonPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JsonPayload.Unmarshal(m, b)
}
func (m *JsonPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JsonPayload.Marshal(b, m, deterministic)
}
func (m *JsonPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JsonPayload.Merge(m, src)
}
func (m *JsonPayload) XXX_Size() int {
	return xxx_messageInfo_JsonPayload.Size(m)
}
func (m *JsonPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_JsonPayload.DiscardUnknown(m)
}

var xxx_messageInfo_JsonPayload proto.InternalMessageInfo

func (m *JsonPayload) GetJson() []byte {
	if m != nil {
		return m.Json
	}
	return nil
}

type MachineQuery struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MachineQuery) Reset()         { *m = MachineQuery{} }
func (m *MachineQuery) String() string { return proto.CompactTextString(m) }
func (*MachineQuery) ProtoMessage()    {}
func (*MachineQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{1}
}

func (m *MachineQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MachineQuery.Unmarshal(m, b)
}
func (m *MachineQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MachineQuery.Marshal(b, m, deterministic)
}
func (m *MachineQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MachineQuery.Merge(m, src)
}
func (m *MachineQuery) XXX_Size() int {
	return xxx_messageInfo_MachineQuery.Size(m)
}
func (m *MachineQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_MachineQuery.DiscardUnknown(m)
}

var xxx_messageInfo_MachineQuery proto.InternalMessageInfo

type Ping struct {
	Nonce                string   `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ping) Reset()         { *m = Ping{} }
func (m *Ping) String() string { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()    {}
func (*Ping) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{2}
}

func (m *Ping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ping.Unmarshal(m, b)
}
func (m *Ping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ping.Marshal(b, m, deterministic)
}
func (m *Ping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ping.Merge(m, src)
}
func (m *Ping) XXX_Size() int {
	return xxx_messageInfo_Ping.Size(m)
}
func (m *Ping) XXX_DiscardUnknown() {
	xxx_messageInfo_Ping.DiscardUnknown(m)
}

var xxx_messageInfo_Ping proto.InternalMessageInfo

func (m *Ping) GetNonce() string {
	if m != nil {
		return m.Nonce
	}
	return ""
}

type Pong struct {
	Nonce                string   `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Code                 int64    `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pong) Reset()         { *m = Pong{} }
func (m *Pong) String() string { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()    {}
func (*Pong) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{3}
}

func (m *Pong) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pong.Unmarshal(m, b)
}
func (m *Pong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pong.Marshal(b, m, deterministic)
}
func (m *Pong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pong.Merge(m, src)
}
func (m *Pong) XXX_Size() int {
	return xxx_messageInfo_Pong.Size(m)
}
func (m *Pong) XXX_DiscardUnknown() {
	xxx_messageInfo_Pong.DiscardUnknown(m)
}

var xxx_messageInfo_Pong proto.InternalMessageInfo

func (m *Pong) GetNonce() string {
	if m != nil {
		return m.Nonce
	}
	return ""
}

func (m *Pong) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

type Query struct {
	Schema               string   `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Uuid                 string   `protobuf:"bytes,3,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Query) Reset()         { *m = Query{} }
func (m *Query) String() string { return proto.CompactTextString(m) }
func (*Query) ProtoMessage()    {}
func (*Query) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{4}
}

func (m *Query) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Query.Unmarshal(m, b)
}
func (m *Query) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Query.Marshal(b, m, deterministic)
}
func (m *Query) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Query.Merge(m, src)
}
func (m *Query) XXX_Size() int {
	return xxx_messageInfo_Query.Size(m)
}
func (m *Query) XXX_DiscardUnknown() {
	xxx_messageInfo_Query.DiscardUnknown(m)
}

var xxx_messageInfo_Query proto.InternalMessageInfo

func (m *Query) GetSchema() string {
	if m != nil {
		return m.Schema
	}
	return ""
}

func (m *Query) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Query) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

type EventList struct {
	List                 []*Event `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventList) Reset()         { *m = EventList{} }
func (m *EventList) String() string { return proto.CompactTextString(m) }
func (*EventList) ProtoMessage()    {}
func (*EventList) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{5}
}

func (m *EventList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventList.Unmarshal(m, b)
}
func (m *EventList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventList.Marshal(b, m, deterministic)
}
func (m *EventList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventList.Merge(m, src)
}
func (m *EventList) XXX_Size() int {
	return xxx_messageInfo_EventList.Size(m)
}
func (m *EventList) XXX_DiscardUnknown() {
	xxx_messageInfo_EventList.DiscardUnknown(m)
}

var xxx_messageInfo_EventList proto.InternalMessageInfo

func (m *EventList) GetList() []*Event {
	if m != nil {
		return m.List
	}
	return nil
}

type StateList struct {
	List                 []*State `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StateList) Reset()         { *m = StateList{} }
func (m *StateList) String() string { return proto.CompactTextString(m) }
func (*StateList) ProtoMessage()    {}
func (*StateList) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{6}
}

func (m *StateList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StateList.Unmarshal(m, b)
}
func (m *StateList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StateList.Marshal(b, m, deterministic)
}
func (m *StateList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StateList.Merge(m, src)
}
func (m *StateList) XXX_Size() int {
	return xxx_messageInfo_StateList.Size(m)
}
func (m *StateList) XXX_DiscardUnknown() {
	xxx_messageInfo_StateList.DiscardUnknown(m)
}

var xxx_messageInfo_StateList proto.InternalMessageInfo

func (m *StateList) GetList() []*State {
	if m != nil {
		return m.List
	}
	return nil
}

type Command struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Schema               string   `protobuf:"bytes,2,opt,name=schema,proto3" json:"schema,omitempty"`
	Action               string   `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	Multiple             uint64   `protobuf:"varint,4,opt,name=multiple,proto3" json:"multiple,omitempty"`
	Payload              []byte   `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	State                []uint64 `protobuf:"varint,6,rep,packed,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Command) Reset()         { *m = Command{} }
func (m *Command) String() string { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()    {}
func (*Command) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{7}
}

func (m *Command) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Command.Unmarshal(m, b)
}
func (m *Command) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Command.Marshal(b, m, deterministic)
}
func (m *Command) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Command.Merge(m, src)
}
func (m *Command) XXX_Size() int {
	return xxx_messageInfo_Command.Size(m)
}
func (m *Command) XXX_DiscardUnknown() {
	xxx_messageInfo_Command.DiscardUnknown(m)
}

var xxx_messageInfo_Command proto.InternalMessageInfo

func (m *Command) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Command) GetSchema() string {
	if m != nil {
		return m.Schema
	}
	return ""
}

func (m *Command) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *Command) GetMultiple() uint64 {
	if m != nil {
		return m.Multiple
	}
	return 0
}

func (m *Command) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *Command) GetState() []uint64 {
	if m != nil {
		return m.State
	}
	return nil
}

type State struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Schema               string               `protobuf:"bytes,2,opt,name=schema,proto3" json:"schema,omitempty"`
	State                []uint64             `protobuf:"varint,3,rep,packed,name=state,proto3" json:"state,omitempty"`
	Head                 string               `protobuf:"bytes,4,opt,name=head,proto3" json:"head,omitempty"`
	Created              *timestamp.Timestamp `protobuf:"bytes,5,opt,name=created,proto3" json:"created,omitempty"`
	Updated              *timestamp.Timestamp `protobuf:"bytes,6,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *State) Reset()         { *m = State{} }
func (m *State) String() string { return proto.CompactTextString(m) }
func (*State) ProtoMessage()    {}
func (*State) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{8}
}

func (m *State) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_State.Unmarshal(m, b)
}
func (m *State) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_State.Marshal(b, m, deterministic)
}
func (m *State) XXX_Merge(src proto.Message) {
	xxx_messageInfo_State.Merge(m, src)
}
func (m *State) XXX_Size() int {
	return xxx_messageInfo_State.Size(m)
}
func (m *State) XXX_DiscardUnknown() {
	xxx_messageInfo_State.DiscardUnknown(m)
}

var xxx_messageInfo_State proto.InternalMessageInfo

func (m *State) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *State) GetSchema() string {
	if m != nil {
		return m.Schema
	}
	return ""
}

func (m *State) GetState() []uint64 {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *State) GetHead() string {
	if m != nil {
		return m.Head
	}
	return ""
}

func (m *State) GetCreated() *timestamp.Timestamp {
	if m != nil {
		return m.Created
	}
	return nil
}

func (m *State) GetUpdated() *timestamp.Timestamp {
	if m != nil {
		return m.Updated
	}
	return nil
}

type EventStatus struct {
	State                *State   `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Code                 int64    `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventStatus) Reset()         { *m = EventStatus{} }
func (m *EventStatus) String() string { return proto.CompactTextString(m) }
func (*EventStatus) ProtoMessage()    {}
func (*EventStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{9}
}

func (m *EventStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventStatus.Unmarshal(m, b)
}
func (m *EventStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventStatus.Marshal(b, m, deterministic)
}
func (m *EventStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventStatus.Merge(m, src)
}
func (m *EventStatus) XXX_Size() int {
	return xxx_messageInfo_EventStatus.Size(m)
}
func (m *EventStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_EventStatus.DiscardUnknown(m)
}

var xxx_messageInfo_EventStatus proto.InternalMessageInfo

func (m *EventStatus) GetState() *State {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *EventStatus) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *EventStatus) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Event struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Schema               string               `protobuf:"bytes,2,opt,name=schema,proto3" json:"schema,omitempty"`
	Action               string               `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	Multiple             uint64               `protobuf:"varint,4,opt,name=multiple,proto3" json:"multiple,omitempty"`
	Payload              *any.Any             `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	State                []uint64             `protobuf:"varint,6,rep,packed,name=state,proto3" json:"state,omitempty"`
	Ts                   *timestamp.Timestamp `protobuf:"bytes,7,opt,name=ts,proto3" json:"ts,omitempty"`
	Uuid                 string               `protobuf:"bytes,8,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Parent               string               `protobuf:"bytes,9,opt,name=parent,proto3" json:"parent,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{10}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Event) GetSchema() string {
	if m != nil {
		return m.Schema
	}
	return ""
}

func (m *Event) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *Event) GetMultiple() uint64 {
	if m != nil {
		return m.Multiple
	}
	return 0
}

func (m *Event) GetPayload() *any.Any {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *Event) GetState() []uint64 {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *Event) GetTs() *timestamp.Timestamp {
	if m != nil {
		return m.Ts
	}
	return nil
}

func (m *Event) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Event) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

type Guard struct {
	Delta                []int64  `protobuf:"varint,1,rep,packed,name=delta,proto3" json:"delta,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Guard) Reset()         { *m = Guard{} }
func (m *Guard) String() string { return proto.CompactTextString(m) }
func (*Guard) ProtoMessage()    {}
func (*Guard) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{11}
}

func (m *Guard) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Guard.Unmarshal(m, b)
}
func (m *Guard) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Guard.Marshal(b, m, deterministic)
}
func (m *Guard) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Guard.Merge(m, src)
}
func (m *Guard) XXX_Size() int {
	return xxx_messageInfo_Guard.Size(m)
}
func (m *Guard) XXX_DiscardUnknown() {
	xxx_messageInfo_Guard.DiscardUnknown(m)
}

var xxx_messageInfo_Guard proto.InternalMessageInfo

func (m *Guard) GetDelta() []int64 {
	if m != nil {
		return m.Delta
	}
	return nil
}

type Transition struct {
	Delta                []int64           `protobuf:"varint,1,rep,packed,name=delta,proto3" json:"delta,omitempty"`
	Role                 string            `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Guards               map[string]*Guard `protobuf:"bytes,3,rep,name=guards,proto3" json:"guards,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Transition) Reset()         { *m = Transition{} }
func (m *Transition) String() string { return proto.CompactTextString(m) }
func (*Transition) ProtoMessage()    {}
func (*Transition) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{12}
}

func (m *Transition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transition.Unmarshal(m, b)
}
func (m *Transition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transition.Marshal(b, m, deterministic)
}
func (m *Transition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transition.Merge(m, src)
}
func (m *Transition) XXX_Size() int {
	return xxx_messageInfo_Transition.Size(m)
}
func (m *Transition) XXX_DiscardUnknown() {
	xxx_messageInfo_Transition.DiscardUnknown(m)
}

var xxx_messageInfo_Transition proto.InternalMessageInfo

func (m *Transition) GetDelta() []int64 {
	if m != nil {
		return m.Delta
	}
	return nil
}

func (m *Transition) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *Transition) GetGuards() map[string]*Guard {
	if m != nil {
		return m.Guards
	}
	return nil
}

type Schemata struct {
	Schema               []string `protobuf:"bytes,1,rep,name=schema,proto3" json:"schema,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Schemata) Reset()         { *m = Schemata{} }
func (m *Schemata) String() string { return proto.CompactTextString(m) }
func (*Schemata) ProtoMessage()    {}
func (*Schemata) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{13}
}

func (m *Schemata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Schemata.Unmarshal(m, b)
}
func (m *Schemata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Schemata.Marshal(b, m, deterministic)
}
func (m *Schemata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Schemata.Merge(m, src)
}
func (m *Schemata) XXX_Size() int {
	return xxx_messageInfo_Schemata.Size(m)
}
func (m *Schemata) XXX_DiscardUnknown() {
	xxx_messageInfo_Schemata.DiscardUnknown(m)
}

var xxx_messageInfo_Schemata proto.InternalMessageInfo

func (m *Schemata) GetSchema() []string {
	if m != nil {
		return m.Schema
	}
	return nil
}

type Machine struct {
	Schema               string                 `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
	Initial              []uint64               `protobuf:"varint,2,rep,packed,name=initial,proto3" json:"initial,omitempty"`
	Capacity             []uint64               `protobuf:"varint,3,rep,packed,name=capacity,proto3" json:"capacity,omitempty"`
	Transitions          map[string]*Transition `protobuf:"bytes,4,rep,name=transitions,proto3" json:"transitions,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Machine) Reset()         { *m = Machine{} }
func (m *Machine) String() string { return proto.CompactTextString(m) }
func (*Machine) ProtoMessage()    {}
func (*Machine) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{14}
}

func (m *Machine) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Machine.Unmarshal(m, b)
}
func (m *Machine) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Machine.Marshal(b, m, deterministic)
}
func (m *Machine) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Machine.Merge(m, src)
}
func (m *Machine) XXX_Size() int {
	return xxx_messageInfo_Machine.Size(m)
}
func (m *Machine) XXX_DiscardUnknown() {
	xxx_messageInfo_Machine.DiscardUnknown(m)
}

var xxx_messageInfo_Machine proto.InternalMessageInfo

func (m *Machine) GetSchema() string {
	if m != nil {
		return m.Schema
	}
	return ""
}

func (m *Machine) GetInitial() []uint64 {
	if m != nil {
		return m.Initial
	}
	return nil
}

func (m *Machine) GetCapacity() []uint64 {
	if m != nil {
		return m.Capacity
	}
	return nil
}

func (m *Machine) GetTransitions() map[string]*Transition {
	if m != nil {
		return m.Transitions
	}
	return nil
}

type MachineList struct {
	List                 []string `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MachineList) Reset()         { *m = MachineList{} }
func (m *MachineList) String() string { return proto.CompactTextString(m) }
func (*MachineList) ProtoMessage()    {}
func (*MachineList) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{15}
}

func (m *MachineList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MachineList.Unmarshal(m, b)
}
func (m *MachineList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MachineList.Marshal(b, m, deterministic)
}
func (m *MachineList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MachineList.Merge(m, src)
}
func (m *MachineList) XXX_Size() int {
	return xxx_messageInfo_MachineList.Size(m)
}
func (m *MachineList) XXX_DiscardUnknown() {
	xxx_messageInfo_MachineList.DiscardUnknown(m)
}

var xxx_messageInfo_MachineList proto.InternalMessageInfo

func (m *MachineList) GetList() []string {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterType((*JsonPayload)(nil), "finite.JsonPayload")
	proto.RegisterType((*MachineQuery)(nil), "finite.MachineQuery")
	proto.RegisterType((*Ping)(nil), "finite.Ping")
	proto.RegisterType((*Pong)(nil), "finite.Pong")
	proto.RegisterType((*Query)(nil), "finite.Query")
	proto.RegisterType((*EventList)(nil), "finite.EventList")
	proto.RegisterType((*StateList)(nil), "finite.StateList")
	proto.RegisterType((*Command)(nil), "finite.Command")
	proto.RegisterType((*State)(nil), "finite.State")
	proto.RegisterType((*EventStatus)(nil), "finite.EventStatus")
	proto.RegisterType((*Event)(nil), "finite.Event")
	proto.RegisterType((*Guard)(nil), "finite.Guard")
	proto.RegisterType((*Transition)(nil), "finite.Transition")
	proto.RegisterMapType((map[string]*Guard)(nil), "finite.Transition.GuardsEntry")
	proto.RegisterType((*Schemata)(nil), "finite.Schemata")
	proto.RegisterType((*Machine)(nil), "finite.Machine")
	proto.RegisterMapType((map[string]*Transition)(nil), "finite.Machine.TransitionsEntry")
	proto.RegisterType((*MachineList)(nil), "finite.MachineList")
}

func init() { proto.RegisterFile("event.proto", fileDescriptor_2d17a9d3f0ddf27e) }

var fileDescriptor_2d17a9d3f0ddf27e = []byte{
	// 809 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0xdd, 0x8e, 0xdc, 0x34,
	0x14, 0xde, 0x64, 0xfe, 0x4f, 0x96, 0x52, 0xcc, 0xaa, 0x0a, 0x23, 0xa0, 0xb3, 0x46, 0x42, 0x23,
	0x2e, 0xb2, 0x68, 0x40, 0x08, 0xc1, 0x15, 0x5b, 0xaa, 0x45, 0x08, 0xa4, 0x21, 0xed, 0x03, 0xe0,
	0x26, 0xde, 0x19, 0x97, 0xc4, 0x8e, 0x62, 0xa7, 0xd2, 0x5c, 0xf2, 0x10, 0x3c, 0x0a, 0x12, 0x2f,
	0xc0, 0xf3, 0xf0, 0x0a, 0xc8, 0xc7, 0x4e, 0x26, 0x93, 0x76, 0x59, 0x6e, 0x7a, 0xe7, 0x13, 0x7f,
	0xe7, 0x9c, 0xcf, 0xdf, 0xf9, 0x09, 0x44, 0xfc, 0x15, 0x97, 0x26, 0xa9, 0x6a, 0x65, 0x14, 0x99,
	0xde, 0x0a, 0x29, 0x0c, 0x5f, 0x3e, 0xde, 0x29, 0xb5, 0x2b, 0xf8, 0x15, 0x7e, 0x7d, 0xd1, 0xdc,
	0x5e, 0x19, 0x51, 0x72, 0x6d, 0x58, 0x59, 0x39, 0xe0, 0xf2, 0x83, 0x21, 0x80, 0xc9, 0x83, 0xbb,
	0xa2, 0x97, 0x10, 0xfd, 0xa8, 0x95, 0xdc, 0xb2, 0x43, 0xa1, 0x58, 0x4e, 0x08, 0x8c, 0x5f, 0x6a,
	0x25, 0xe3, 0x60, 0x15, 0xac, 0xcf, 0x53, 0x3c, 0xd3, 0x07, 0x70, 0xfe, 0x33, 0xcb, 0xf6, 0x42,
	0xf2, 0x5f, 0x1a, 0x5e, 0x1f, 0xe8, 0x87, 0x30, 0xde, 0x0a, 0xb9, 0x23, 0x17, 0x30, 0x91, 0x4a,
	0x66, 0x1c, 0xc1, 0x8b, 0xd4, 0x19, 0xf4, 0x73, 0x18, 0x6f, 0xd5, 0x5d, 0xb7, 0x36, 0x7e, 0xa6,
	0x72, 0x1e, 0x87, 0xab, 0x60, 0x3d, 0x4a, 0xf1, 0x4c, 0x9f, 0xc0, 0x04, 0x03, 0x93, 0x47, 0x30,
	0xd5, 0xd9, 0x9e, 0x97, 0xcc, 0xfb, 0x78, 0x8b, 0x3c, 0x80, 0x50, 0xe4, 0xe8, 0xb2, 0x48, 0x43,
	0x81, 0x24, 0x9b, 0x46, 0xe4, 0xf1, 0x08, 0xbf, 0xe0, 0x99, 0x26, 0xb0, 0x78, 0x6a, 0xa5, 0xf9,
	0x49, 0x68, 0x43, 0x2e, 0x61, 0x5c, 0x08, 0x6d, 0xe2, 0x60, 0x35, 0x5a, 0x47, 0x9b, 0x77, 0x12,
	0xa7, 0x53, 0x82, 0x80, 0x14, 0xaf, 0x2c, 0xfe, 0x99, 0x61, 0x86, 0xff, 0x17, 0x1e, 0x01, 0x1e,
	0xff, 0x47, 0x00, 0xb3, 0x27, 0xaa, 0x2c, 0x99, 0xcc, 0x3d, 0x9f, 0xa0, 0xe3, 0x73, 0xe4, 0x1d,
	0x9e, 0xf0, 0x7e, 0x04, 0x53, 0x96, 0x19, 0xa1, 0xa4, 0x67, 0xea, 0x2d, 0xb2, 0x84, 0x79, 0xd9,
	0x14, 0x46, 0x54, 0x05, 0x8f, 0xc7, 0xab, 0x60, 0x3d, 0x4e, 0x3b, 0x9b, 0xc4, 0x30, 0xab, 0x5c,
	0x2d, 0xe2, 0x09, 0xd6, 0xa0, 0x35, 0xad, 0xa0, 0xda, 0x12, 0x8a, 0xa7, 0xab, 0xd1, 0x7a, 0x9c,
	0x3a, 0x83, 0xfe, 0x1d, 0xc0, 0x04, 0x79, 0xfe, 0x6f, 0x56, 0x5d, 0x9c, 0x51, 0x2f, 0x8e, 0xd5,
	0x74, 0xcf, 0x59, 0x8e, 0x7c, 0x16, 0x29, 0x9e, 0xc9, 0x97, 0x30, 0xcb, 0x6a, 0xce, 0x0c, 0x77,
	0x5c, 0xa2, 0xcd, 0x32, 0x71, 0x8d, 0x94, 0xb4, 0x8d, 0x94, 0x3c, 0x6f, 0x3b, 0x2d, 0x6d, 0xa1,
	0xd6, 0xab, 0xa9, 0x72, 0xf4, 0x9a, 0xde, 0xef, 0xe5, 0xa1, 0xf4, 0x57, 0x88, 0xb0, 0x3c, 0xf6,
	0x2d, 0x8d, 0x26, 0x9f, 0xb4, 0x24, 0x03, 0x0c, 0x31, 0x28, 0xc9, 0x91, 0xf3, 0xb0, 0x99, 0xac,
	0x7e, 0x25, 0xd7, 0x9a, 0xed, 0xb8, 0x17, 0xbd, 0x35, 0xe9, 0xef, 0x21, 0x4c, 0x30, 0xc5, 0x5b,
	0xad, 0x5f, 0x72, 0x5a, 0xbf, 0x68, 0x73, 0xf1, 0xda, 0xeb, 0xbf, 0x93, 0x87, 0x7b, 0xaa, 0x4a,
	0x3e, 0x83, 0xd0, 0xe8, 0x78, 0x76, 0xaf, 0x7c, 0xa1, 0xd1, 0xdd, 0x34, 0xcc, 0x8f, 0xd3, 0x60,
	0x99, 0x57, 0xac, 0xe6, 0xd2, 0xc4, 0x0b, 0xc7, 0xdc, 0x59, 0xf4, 0x23, 0x98, 0xdc, 0x34, 0xac,
	0xc6, 0xb4, 0x39, 0x2f, 0x0c, 0xc3, 0x96, 0x1f, 0xa5, 0xce, 0xa0, 0x7f, 0x05, 0x00, 0xcf, 0x6b,
	0x26, 0xb5, 0xc0, 0x77, 0xbe, 0x11, 0x64, 0xf3, 0xd5, 0xaa, 0xe0, 0x5e, 0x2b, 0x3c, 0x93, 0xaf,
	0x60, 0xba, 0xb3, 0x71, 0x35, 0x36, 0x55, 0xb4, 0xf9, 0xb8, 0xad, 0xd7, 0x31, 0x5a, 0x82, 0x89,
	0xf5, 0x53, 0x69, 0xea, 0x43, 0xea, 0xd1, 0xcb, 0x1f, 0x20, 0xea, 0x7d, 0x26, 0x0f, 0x61, 0xf4,
	0x1b, 0x3f, 0xf8, 0xca, 0xd8, 0xa3, 0xed, 0x83, 0x57, 0xac, 0x68, 0x5c, 0xb6, 0x5e, 0x1f, 0xa0,
	0x57, 0xea, 0xee, 0xbe, 0x09, 0xbf, 0x0e, 0x28, 0x85, 0xf9, 0x33, 0xac, 0x9a, 0x61, 0x27, 0x7b,
	0x64, 0x74, 0xac, 0x27, 0xfd, 0x27, 0x80, 0x99, 0xdf, 0x64, 0x77, 0xee, 0x9a, 0x18, 0x66, 0x36,
	0x83, 0x60, 0x45, 0x1c, 0x62, 0x45, 0x5a, 0xd3, 0x56, 0x3d, 0x63, 0x15, 0xcb, 0x84, 0x39, 0xf8,
	0xd1, 0xe9, 0x6c, 0x72, 0x0d, 0x91, 0xe9, 0x5e, 0xaa, 0xe3, 0x31, 0x8a, 0xb0, 0x6a, 0xc9, 0xfa,
	0x9c, 0x3d, 0x31, 0xbc, 0x0c, 0x7d, 0xa7, 0x65, 0x0a, 0x0f, 0x87, 0x80, 0x37, 0x08, 0xb2, 0x3e,
	0x15, 0x84, 0xbc, 0x2e, 0x74, 0x5f, 0x95, 0x4b, 0x88, 0x7c, 0x72, 0xdc, 0x73, 0xa4, 0xb7, 0xe7,
	0x16, 0x6e, 0xb1, 0x6d, 0xfe, 0x0c, 0x01, 0xfc, 0xe4, 0xa9, 0x9a, 0x93, 0x4f, 0x61, 0xea, 0x47,
	0xf0, 0xbc, 0x0d, 0x6d, 0x97, 0xfd, 0xf2, 0x68, 0x29, 0xb9, 0xa3, 0x67, 0xe4, 0x5b, 0x38, 0xb7,
	0x21, 0x7d, 0x74, 0x4d, 0x2e, 0x06, 0x8f, 0xc5, 0x8d, 0xbe, 0x7c, 0x7f, 0xf0, 0xd5, 0xba, 0xd0,
	0x33, 0x92, 0x00, 0xdc, 0xf0, 0xd6, 0x97, 0x74, 0x45, 0x75, 0x3e, 0xef, 0x0e, 0x7c, 0xe8, 0x19,
	0xd9, 0xc0, 0xfc, 0x7b, 0xa1, 0x2b, 0x66, 0xb2, 0x3d, 0xe9, 0xae, 0xfd, 0x36, 0x3e, 0xe6, 0xe8,
	0xed, 0x0f, 0xcc, 0x31, 0xbf, 0xe1, 0xc6, 0x0d, 0xfc, 0x20, 0xc3, 0x7b, 0x27, 0x1e, 0x1d, 0x27,
	0x8b, 0x77, 0xab, 0xf4, 0x2e, 0x7c, 0xf7, 0xc7, 0xa0, 0x67, 0xd7, 0x57, 0xf0, 0x38, 0x53, 0xa5,
	0x1d, 0xca, 0x97, 0x3c, 0x33, 0xc9, 0x2d, 0xcb, 0x8c, 0x2a, 0x5b, 0x20, 0xfe, 0xa5, 0xaf, 0x9d,
	0xae, 0x5b, 0x3b, 0xb6, 0xdb, 0xe0, 0xc5, 0x14, 0xe7, 0xf7, 0x8b, 0x7f, 0x03, 0x00, 0x00, 0xff,
	0xff, 0x92, 0xc5, 0x9a, 0xdd, 0xc3, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EventStoreClient is the client API for EventStore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EventStoreClient interface {
	Status(ctx context.Context, in *Ping, opts ...grpc.CallOption) (*Pong, error)
	ListMachines(ctx context.Context, in *MachineQuery, opts ...grpc.CallOption) (*MachineList, error)
	GetMachine(ctx context.Context, in *Query, opts ...grpc.CallOption) (*Machine, error)
	Dispatch(ctx context.Context, in *Command, opts ...grpc.CallOption) (*EventStatus, error)
	GetEvent(ctx context.Context, in *Query, opts ...grpc.CallOption) (*EventList, error)
	GetState(ctx context.Context, in *Query, opts ...grpc.CallOption) (*StateList, error)
}

type eventStoreClient struct {
	cc *grpc.ClientConn
}

func NewEventStoreClient(cc *grpc.ClientConn) EventStoreClient {
	return &eventStoreClient{cc}
}

func (c *eventStoreClient) Status(ctx context.Context, in *Ping, opts ...grpc.CallOption) (*Pong, error) {
	out := new(Pong)
	err := c.cc.Invoke(ctx, "/finite.EventStore/Status", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventStoreClient) ListMachines(ctx context.Context, in *MachineQuery, opts ...grpc.CallOption) (*MachineList, error) {
	out := new(MachineList)
	err := c.cc.Invoke(ctx, "/finite.EventStore/ListMachines", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventStoreClient) GetMachine(ctx context.Context, in *Query, opts ...grpc.CallOption) (*Machine, error) {
	out := new(Machine)
	err := c.cc.Invoke(ctx, "/finite.EventStore/GetMachine", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventStoreClient) Dispatch(ctx context.Context, in *Command, opts ...grpc.CallOption) (*EventStatus, error) {
	out := new(EventStatus)
	err := c.cc.Invoke(ctx, "/finite.EventStore/Dispatch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventStoreClient) GetEvent(ctx context.Context, in *Query, opts ...grpc.CallOption) (*EventList, error) {
	out := new(EventList)
	err := c.cc.Invoke(ctx, "/finite.EventStore/GetEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventStoreClient) GetState(ctx context.Context, in *Query, opts ...grpc.CallOption) (*StateList, error) {
	out := new(StateList)
	err := c.cc.Invoke(ctx, "/finite.EventStore/GetState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventStoreServer is the server API for EventStore service.
type EventStoreServer interface {
	Status(context.Context, *Ping) (*Pong, error)
	ListMachines(context.Context, *MachineQuery) (*MachineList, error)
	GetMachine(context.Context, *Query) (*Machine, error)
	Dispatch(context.Context, *Command) (*EventStatus, error)
	GetEvent(context.Context, *Query) (*EventList, error)
	GetState(context.Context, *Query) (*StateList, error)
}

// UnimplementedEventStoreServer can be embedded to have forward compatible implementations.
type UnimplementedEventStoreServer struct {
}

func (*UnimplementedEventStoreServer) Status(ctx context.Context, req *Ping) (*Pong, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Status not implemented")
}
func (*UnimplementedEventStoreServer) ListMachines(ctx context.Context, req *MachineQuery) (*MachineList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMachines not implemented")
}
func (*UnimplementedEventStoreServer) GetMachine(ctx context.Context, req *Query) (*Machine, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMachine not implemented")
}
func (*UnimplementedEventStoreServer) Dispatch(ctx context.Context, req *Command) (*EventStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Dispatch not implemented")
}
func (*UnimplementedEventStoreServer) GetEvent(ctx context.Context, req *Query) (*EventList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEvent not implemented")
}
func (*UnimplementedEventStoreServer) GetState(ctx context.Context, req *Query) (*StateList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetState not implemented")
}

func RegisterEventStoreServer(s *grpc.Server, srv EventStoreServer) {
	s.RegisterService(&_EventStore_serviceDesc, srv)
}

func _EventStore_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Ping)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventStoreServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/finite.EventStore/Status",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventStoreServer).Status(ctx, req.(*Ping))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventStore_ListMachines_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MachineQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventStoreServer).ListMachines(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/finite.EventStore/ListMachines",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventStoreServer).ListMachines(ctx, req.(*MachineQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventStore_GetMachine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Query)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventStoreServer).GetMachine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/finite.EventStore/GetMachine",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventStoreServer).GetMachine(ctx, req.(*Query))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventStore_Dispatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Command)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventStoreServer).Dispatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/finite.EventStore/Dispatch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventStoreServer).Dispatch(ctx, req.(*Command))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventStore_GetEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Query)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventStoreServer).GetEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/finite.EventStore/GetEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventStoreServer).GetEvent(ctx, req.(*Query))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventStore_GetState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Query)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventStoreServer).GetState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/finite.EventStore/GetState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventStoreServer).GetState(ctx, req.(*Query))
	}
	return interceptor(ctx, in, info, handler)
}

var _EventStore_serviceDesc = grpc.ServiceDesc{
	ServiceName: "finite.EventStore",
	HandlerType: (*EventStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _EventStore_Status_Handler,
		},
		{
			MethodName: "ListMachines",
			Handler:    _EventStore_ListMachines_Handler,
		},
		{
			MethodName: "GetMachine",
			Handler:    _EventStore_GetMachine_Handler,
		},
		{
			MethodName: "Dispatch",
			Handler:    _EventStore_Dispatch_Handler,
		},
		{
			MethodName: "GetEvent",
			Handler:    _EventStore_GetEvent_Handler,
		},
		{
			MethodName: "GetState",
			Handler:    _EventStore_GetState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "event.proto",
}
